In [317]:
import numpy as np
import pandas as pd
from sklearn.calibration import LabelEncoder

In [318]:
housing = pd.read_csv('Housing.csv')

In [319]:
X = housing.iloc[:,1:]
y = housing.iloc[:,0]

In [320]:
X

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [321]:
xe = LabelEncoder()
for i in range(5,10):
    X.iloc[:,i] = xe.fit_transform(X.iloc[:,i])
for i in range(1,3):
    X.iloc[:,-i] = xe.fit_transform(X.iloc[:,-i])

X.mainroad = xe.fit_transform(X.mainroad)

In [322]:
X

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0
1,8960,4,4,4,1,0,0,0,1,3,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1
3,7500,4,2,2,1,0,1,0,1,3,1,0
4,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,1,0,1,0,0,2,0,2
541,2400,3,1,1,0,0,0,0,0,0,0,1
542,3620,2,1,1,1,0,0,0,0,0,0,2
543,2910,3,1,1,0,0,0,0,0,0,0,0
544,3850,3,1,2,1,0,0,0,0,0,0,2

In [323]:
y = y.to_numpy().reshape(-1,1)

In [324]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=np.random.randint(0, 100000))

In [325]:
from sklearn.linear_model import LinearRegression


reg = LinearRegression()

In [326]:
reg.fit(X_train,y_train)

LinearRegression()

In [327]:
y_pred = (reg.predict(X_test).reshape(-1,1) // 1)

In [328]:
[y_pred,y_test]

[array([[4458529.],
        [4989049.],
        [4445504.],
        [5111398.],
        [6483889.],
        [3396097.],
        [4674565.],
        [3384588.],
        [4543468.],
        [6889179.],
        [5398916.],
        [5664026.],
        [4302056.],
        [6082487.],
        [6245210.],
        [7207294.],
        [6636055.],
        [2910825.],
        [3992187.],
        [3031999.],
        [5681296.],
        [5566837.],
        [4249964.],
        [6430201.],
        [8429803.],
        [5508761.],
        [5176519.],
        [2925029.],
        [7525515.],
        [7054598.],
        [6194724.],
        [5862029.],
        [2728570.],
        [2869654.],
        [5260259.],
        [5790453.],
        [3189809.],
        [4169869.],
        [3012230.],
        [5767006.],
        [5575447.],
        [6320336.],
        [5441729.],
        [4256137.],
        [3740857.],
        [5131328.],
        [5953917.],
        [7239227.],
        [4311312.],
        [4214332.],
        [5645236.],
        [3010943.],
        [4042275.],
        [6708802.],
        [5033885.],
        [5585332.],
        [3333668.],
        [7074966.],
        [6293574.],
        [7212676.],
        [5090557.],
        [4823326.],
        [3499771.],
        [3468133.],
        [4857649.],
        [2888735.],
        [3109368.],
        [5835756.],
        [3665960.],
        [3475481.],
        [6078269.],
        [6148067.],
        [3164468.],
        [2825900.],
        [5061594.],
        [3194035.],
        [6590007.],
        [2108449.],
        [3590726.],
        [4785257.],
        [4679225.],
        [6217767.],
        [6599222.],
        [4456034.],
        [3405982.],
        [4046198.],
        [2423933.],
        [5744549.],
        [3359128.],
        [6143388.],
        [7639322.],
        [5216892.],
        [4027471.],
        [5203053.],
        [3642991.],
        [2765953.],
        [3153300.],
        [3234201.],
        [2676769.],
        [4436711.],
        [4443653.],
        [4479505.],
        [4060124.],
        [5550962.],
        [2500503.],
        [6104341.],
        [3573934.],
        [3889988.],
        [7559572.],
        [4566816.],
        [4533698.],
        [5440938.],
        [4914709.],
        [3316455.],
        [3465423.],
        [4060882.],
        [6400380.],
        [5063501.],
        [4271926.],
        [2850667.],
        [5836591.],
        [3553437.],
        [2785463.],
        [5415181.],
        [7946025.],
        [3802561.],
        [5343636.],
        [6254913.],
        [3574684.],
        [8047704.],
        [6162536.],
        [4390493.],
        [3604994.],
        [6294609.],
        [5864333.],
        [5250524.],
        [5698927.],
        [2808333.],
        [4393974.],
        [4584960.],
        [3004145.],
        [3527368.],
        [3897181.],
        [2580431.],
        [4095645.],
        [2559045.],
        [6903558.],
        [3366093.],
        [3226170.],
        [5252636.],
        [4179408.],
        [5515280.],
        [2988065.],
        [6734851.],
        [5620916.],
        [2899988.],
        [3452386.],
        [5729884.],
        [7114013.],
        [6442365.],
        [3768367.],
        [3608598.],
        [4501147.],
        [4984061.],
        [4456362.],
        [4289094.],
        [5193218.],
        [4609989.],
        [4439497.],
        [4189929.],
        [5286921.],
        [4274583.],
        [3394977.],
        [4465837.],
        [4122438.],
        [7855096.],
        [4598593.],
        [3480690.],
        [2230048.],
        [5047855.],
        [6416351.],
        [5518742.]]),
 array([[ 4480000],
        [ 4277000],
        [ 3780000],
        [ 4690000],
        [ 8680000],
        [ 4340000],
        [ 4473000],
        [ 3115000],
        [ 3850000],
        [ 7343000],
        [ 5803000],
        [ 5950000],
        [ 3290000],
        [ 9240000],
        [ 3500000],
        [ 8575000],
        [ 6090000],
        [ 3220000],
        [ 3500000],
        [ 3010000],
        [ 4690000],
        [ 5250000],
        [ 4200000],
        [ 5565000],
        [10150000],
        [ 3150000],
        [ 5250000],
        [ 3150000],
        [ 6440000],
        [ 6650000],
        [ 5530000],
        [ 5600000],
        [ 3290000],
        [ 2590000],
        [ 5285000],
        [ 5383000],
        [ 1960000],
        [ 4515000],
        [ 2940000],
        [ 5425000],
        [ 6090000],
        [ 6195000],
        [ 4305000],
        [ 4165000],
        [ 3290000],
        [ 5740000],
        [ 6300000],
        [ 9100000],
        [ 2940000],
        [ 4907000],
        [ 5005000],
        [ 3850000],
        [ 3010000],
        [ 7700000],
        [ 3773000],
        [ 5250000],
        [ 3500000],
        [ 6650000],
        [ 6650000],
        [ 7525000],
        [ 3773000],
        [ 3920000],
        [ 2870000],
        [ 3535000],
        [ 5810000],
        [ 3780000],
        [ 3710000],
        [ 6300000],
        [ 3129000],
        [ 3500000],
        [ 6790000],
        [ 7875000],
        [ 3080000],
        [ 3150000],
        [ 5523000],
        [ 3500000],
        [ 4550000],
        [ 2604000],
        [ 4319000],
        [ 4830000],
        [ 4130000],
        [ 4900000],
        [ 8295000],
        [ 3290000],
        [ 3500000],
        [ 3850000],
        [ 1855000],
        [ 4025000],
        [ 3010000],
        [ 5110000],
        [ 7350000],
        [ 5880000],
        [ 4515000],
        [ 4473000],
        [ 3500000],
        [ 2450000],
        [ 2660000],
        [ 2940000],
        [ 3465000],
        [ 4585000],
        [ 4480000],
        [ 4340000],
        [ 4200000],
        [ 5810000],
        [ 2940000],
        [ 5320000],
        [ 2975000],
        [ 4900000],
        [ 9870000],
        [ 5243000],
        [ 3290000],
        [ 5530000],
        [ 3990000],
        [ 2100000],
        [ 2520000],
        [ 3500000],
        [ 4340000],
        [ 5110000],
        [ 4620000],
        [ 3150000],
        [ 6615000],
        [ 4550000],
        [ 4200000],
        [ 4025000],
        [ 9681000],
        [ 4095000],
        [ 6650000],
        [ 7350000],
        [ 3290000],
        [13300000],
        [ 5215000],
        [ 4690000],
        [ 3150000],
        [ 6300000],
        [ 5950000],
        [ 6895000],
        [ 5229000],
        [ 2450000],
        [ 4620000],
        [ 3010000],
        [ 3115000],
        [ 3605000],
        [ 4403000],
        [ 2380000],
        [ 4410000],
        [ 2310000],
        [ 8400000],
        [ 3010000],
        [ 4865000],
        [ 7070000],
        [ 4123000],
        [ 6510000],
        [ 2660000],
        [ 6300000],
        [ 5600000],
        [ 2100000],
        [ 3220000],
        [ 4060000],
        [ 7000000],
        [ 5460000],
        [ 3325000],
        [ 4900000],
        [ 4550000],
        [ 5145000],
        [ 3640000],
        [ 4200000],
        [ 3500000],
        [ 3885000],
        [ 3430000],
        [ 3640000],
        [ 3990000],
        [ 3143000],
        [ 3745000],
        [ 4543000],
        [ 4095000],
        [10850000],
        [ 4235000],
        [ 2730000],
        [ 2275000],
        [ 4900000],
        [ 8890000],
        [ 5215000]], dtype=int64)]

In [329]:
np.hstack((y_pred,y_test))

array([[ 4458529.,  4480000.],
       [ 4989049.,  4277000.],
       [ 4445504.,  3780000.],
       [ 5111398.,  4690000.],
       [ 6483889.,  8680000.],
       [ 3396097.,  4340000.],
       [ 4674565.,  4473000.],
       [ 3384588.,  3115000.],
       [ 4543468.,  3850000.],
       [ 6889179.,  7343000.],
       [ 5398916.,  5803000.],
       [ 5664026.,  5950000.],
       [ 4302056.,  3290000.],
       [ 6082487.,  9240000.],
       [ 6245210.,  3500000.],
       [ 7207294.,  8575000.],
       [ 6636055.,  6090000.],
       [ 2910825.,  3220000.],
       [ 3992187.,  3500000.],
       [ 3031999.,  3010000.],
       [ 5681296.,  4690000.],
       [ 5566837.,  5250000.],
       [ 4249964.,  4200000.],
       [ 6430201.,  5565000.],
       [ 8429803., 10150000.],
       [ 5508761.,  3150000.],
       [ 5176519.,  5250000.],
       [ 2925029.,  3150000.],
       [ 7525515.,  6440000.],
       [ 7054598.,  6650000.],
       [ 6194724.,  5530000.],
       [ 5862029.,  5600000.],
       [ 2728570.,  3290000.],
       [ 2869654.,  2590000.],
       [ 5260259.,  5285000.],
       [ 5790453.,  5383000.],
       [ 3189809.,  1960000.],
       [ 4169869.,  4515000.],
       [ 3012230.,  2940000.],
       [ 5767006.,  5425000.],
       [ 5575447.,  6090000.],
       [ 6320336.,  6195000.],
       [ 5441729.,  4305000.],
       [ 4256137.,  4165000.],
       [ 3740857.,  3290000.],
       [ 5131328.,  5740000.],
       [ 5953917.,  6300000.],
       [ 7239227.,  9100000.],
       [ 4311312.,  2940000.],
       [ 4214332.,  4907000.],
       [ 5645236.,  5005000.],
       [ 3010943.,  3850000.],
       [ 4042275.,  3010000.],
       [ 6708802.,  7700000.],
       [ 5033885.,  3773000.],
       [ 5585332.,  5250000.],
       [ 3333668.,  3500000.],
       [ 7074966.,  6650000.],
       [ 6293574.,  6650000.],
       [ 7212676.,  7525000.],
       [ 5090557.,  3773000.],
       [ 4823326.,  3920000.],
       [ 3499771.,  2870000.],
       [ 3468133.,  3535000.],
       [ 4857649.,  5810000.],
       [ 2888735.,  3780000.],
       [ 3109368.,  3710000.],
       [ 5835756.,  6300000.],
       [ 3665960.,  3129000.],
       [ 3475481.,  3500000.],
       [ 6078269.,  6790000.],
       [ 6148067.,  7875000.],
       [ 3164468.,  3080000.],
       [ 2825900.,  3150000.],
       [ 5061594.,  5523000.],
       [ 3194035.,  3500000.],
       [ 6590007.,  4550000.],
       [ 2108449.,  2604000.],
       [ 3590726.,  4319000.],
       [ 4785257.,  4830000.],
       [ 4679225.,  4130000.],
       [ 6217767.,  4900000.],
       [ 6599222.,  8295000.],
       [ 4456034.,  3290000.],
       [ 3405982.,  3500000.],
       [ 4046198.,  3850000.],
       [ 2423933.,  1855000.],
       [ 5744549.,  4025000.],
       [ 3359128.,  3010000.],
       [ 6143388.,  5110000.],
       [ 7639322.,  7350000.],
       [ 5216892.,  5880000.],
       [ 4027471.,  4515000.],
       [ 5203053.,  4473000.],
       [ 3642991.,  3500000.],
       [ 2765953.,  2450000.],
       [ 3153300.,  2660000.],
       [ 3234201.,  2940000.],
       [ 2676769.,  3465000.],
       [ 4436711.,  4585000.],
       [ 4443653.,  4480000.],
       [ 4479505.,  4340000.],
       [ 4060124.,  4200000.],
       [ 5550962.,  5810000.],
       [ 2500503.,  2940000.],
       [ 6104341.,  5320000.],
       [ 3573934.,  2975000.],
       [ 3889988.,  4900000.],
       [ 7559572.,  9870000.],
       [ 4566816.,  5243000.],
       [ 4533698.,  3290000.],
       [ 5440938.,  5530000.],
       [ 4914709.,  3990000.],
       [ 3316455.,  2100000.],
       [ 3465423.,  2520000.],
       [ 4060882.,  3500000.],
       [ 6400380.,  4340000.],
       [ 5063501.,  5110000.],
       [ 4271926.,  4620000.],
       [ 2850667.,  3150000.],
       [ 5836591.,  6615000.],
       [ 3553437.,  4550000.],
       [ 2785463.,  4200000.],
       [ 5415181.,  4025000.],
       [ 7946025.,  9681000.],
       [ 3802561.,  4095000.],
       [ 5343636.,  6650000.],
       [ 6254913.,  7350000.],
       [ 3574684.,  3290000.],
       [ 8047704., 13300000.],
       [ 6162536.,  5215000.],
       [ 4390493.,  4690000.],
       [ 3604994.,  3150000.],
       [ 6294609.,  6300000.],
       [ 5864333.,  5950000.],
       [ 5250524.,  6895000.],
       [ 5698927.,  5229000.],
       [ 2808333.,  2450000.],
       [ 4393974.,  4620000.],
       [ 4584960.,  3010000.],
       [ 3004145.,  3115000.],
       [ 3527368.,  3605000.],
       [ 3897181.,  4403000.],
       [ 2580431.,  2380000.],
       [ 4095645.,  4410000.],
       [ 2559045.,  2310000.],
       [ 6903558.,  8400000.],
       [ 3366093.,  3010000.],
       [ 3226170.,  4865000.],
       [ 5252636.,  7070000.],
       [ 4179408.,  4123000.],
       [ 5515280.,  6510000.],
       [ 2988065.,  2660000.],
       [ 6734851.,  6300000.],
       [ 5620916.,  5600000.],
       [ 2899988.,  2100000.],
       [ 3452386.,  3220000.],
       [ 5729884.,  4060000.],
       [ 7114013.,  7000000.],
       [ 6442365.,  5460000.],
       [ 3768367.,  3325000.],
       [ 3608598.,  4900000.],
       [ 4501147.,  4550000.],
       [ 4984061.,  5145000.],
       [ 4456362.,  3640000.],
       [ 4289094.,  4200000.],
       [ 5193218.,  3500000.],
       [ 4609989.,  3885000.],
       [ 4439497.,  3430000.],
       [ 4189929.,  3640000.],
       [ 5286921.,  3990000.],
       [ 4274583.,  3143000.],
       [ 3394977.,  3745000.],
       [ 4465837.,  4543000.],
       [ 4122438.,  4095000.],
       [ 7855096., 10850000.],
       [ 4598593.,  4235000.],
       [ 3480690.,  2730000.],
       [ 2230048.,  2275000.],
       [ 5047855.,  4900000.],
       [ 6416351.,  8890000.],
       [ 5518742.,  5215000.]])

In [330]:

from sklearn.metrics import mean_absolute_error


mean_absolute_error(y_test, y_pred)

731007.3351648352